# Save IP addresses and SSH info to file
resource "local_file" "inventory" {
  content = templatefile("${path.module}/templates/inventory.tftpl", {
    droplets     = digitalocean_droplet.os_family
    ssh_key_path = local.private_key_path
  })
  filename = "${path.module}/output/inventory.ini"

  depends_on = [null_resource.wait_for_ssh]
}

resource "local_file" "hosts_info" {
  content = templatefile("${path.module}/templates/hosts_info.tftpl", {
    droplets     = digitalocean_droplet.os_family
    ssh_key_path = local.private_key_path
  })
  filename = "${path.module}/output/hosts_info.txt"

  depends_on = [null_resource.wait_for_ssh]
}

# Generate Ansible run script for Windows
resource "local_file" "ansible_run_script" {
  content = <<-EOT
@echo off
REM Run Ansible Playbook from Windows
REM Generated by Terraform

echo =========================================
echo   Running Ansible Playbook
echo =========================================

REM Option 1: Run via WSL (if Ansible is installed in WSL)
REM wsl ansible-playbook -i output/inventory.ini ansible_install_software.yml

REM Option 2: Run via Python/pip Ansible on Windows
ansible-playbook -i "${replace(abspath("${path.module}/output/inventory.ini"), "\\", "/")}" "${replace(abspath("${path. module}/ansible_install_software.yml"), "\\", "/")}"

echo. 
echo =========================================
echo   Ansible Playbook Complete
echo =========================================
pause
EOT
  filename = "${path.module}/run_ansible.bat"

  depends_on = [local_file.inventory]
}

# Output to console
output "droplet_ips" {
  description = "IP addresses of created droplets"
  value = {
    for droplet in digitalocean_droplet.os_family : 
    droplet.name => droplet.ipv4_address
  }
}

output "ssh_private_key_path" {
  description = "Path to SSH private key"
  # value       = abspath(local_file.private_key.filename)
  value       = local.private_key_path
}

output "ssh_connection_commands" {
  description = "SSH commands to connect to each droplet"
  value = [
    for droplet in digitalocean_droplet.os_family :
    "ssh -i \"${local.private_key_path}\" root@${droplet.ipv4_address}"
  ]
}

output "ansible_command" {
  description = "Command to run Ansible playbook"
  value       = "ansible-playbook -i ${path.module}/output/inventory.ini ansible_install_software.yml"
}

output "inventory_file" {
  description = "Path to Ansible inventory file"
  value       = abspath("${path.module}/output/inventory.ini")
}